freebsd_instance:
  image: freebsd-12-0-release-amd64

task:
  install_script: pkg install -y
        meson ninja pkgconf python2
  script:
      - meson builddir --warnlevel 3 --buildtype release
      - ninja -v -C builddir
