language: C
dist: xenial
sudo: true

before_install:
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq ninja-build
  - sudo apt install python3
  - sudo apt install python3-pip
  - sudo apt install python3-setuptools
  - pip3 install meson

script:
  - meson builddir
  - ninja -C builddir

